spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: "classpath:db/migration,filesystem:/opt/migration"
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
    org.flywaydb: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
